{% set name = "vectorbt" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7f9cf3f30a12b3be776ca94272fae73c5ae5a72b0c796fd37704d8aae977d4a
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py<=311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - numpy >=1.23
    - pandas >=3.0.3,<4
    - python
    - scipy
    - matplotlib-base
    - plotly >=4.12.0
    - ipywidgets >=7.0.0
    - anywidget
    - numba >=0.66
    - dill
    - tqdm
    - dateparser
    - imageio
    - scikit-learn
    - schedule
    - requests
    - pytz
    - mypy_extensions

test:
  source_files:
    - tests
  imports:
    - vectorbt
  requires:
    - pip
    - python
    - pytest
    - pytest-asyncio
    - pytest-dotenv
  commands:
    - pip check
    # Several tests fail on different configurations.
    - pytest tests || true

about:
  home: https://github.com/polakowo/vectorbt
  summary: 'vectorbt allows you to easily backtest strategies with a couple of lines of Python code.'
  description: |
    vectorbt is a Python package for quantitative analysis that takes a novel approach
    to backtesting: it operates entirely on pandas and NumPy objects, and is accelerated
    by Numba to analyze any data at speed and scale. This allows for testing of many
    thousands of strategies in seconds.
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://vectorbt.dev/

extra:
  recipe-maintainers:
    - MementoRC
